language: python
python:
 - "3.8"
 - "3.7"
 - "3.6"
dist: xenial
install:
- pip install poetry
- poetry install
script:
- pylint --load-plugins pylint_quotes fs/onedrivefs/ tests/
- coverage run --source . -m pytest
after_success:
- coveralls
