language: python
python:
 - "3.8"
 - "3.7"
 - "3.6"
dist: xenial
install:
- pip install fs requests requests-oauthlib pyperclip pylint pytest pyperclip python-coveralls coverage
script:
- pylint fs/onedrivefs/
- pylint tests/
- coverage run --source . -m pytest
after_success:
- coveralls
