[tool.poetry]
name = "fs.onedrivefs"
packages = [
    { include = "fs"}
]
version = "0.2.4"
description = "Pyfilesystem2 implementation for OneDrive using Microsoft Graph API"
authors = ["Rehan Khwaja <rehan@khwaja.name>"]
license = "MIT"
homepage = "https://github.com/rkhwaja/fs.onedrivefs"
keywords = ["filesystem", "Pyfilesystem2", "onedrive"]
readme = "README.rst"

[tool.poetry.dependencies]
python = ">=3.6"
fs = ">=2.0.6"
requests = "^2.20"
requests-oauthlib = "^1.0"

[tool.poetry.dev-dependencies]
pyperclip = "^1.7"
pytest = "^3.10"
pylint = ">=2.5.3"
python-coveralls = "^2.9.3"
pylint-quotes = "^0.2.1"

[tool.poetry.plugins] # Optional super table

[tool.poetry.plugins."fs.opener"]
"onedrive" = "fs.onedrivefs.opener:OneDriveFSOpener"

[tool.pylint.format]
indent-string = "\t"
max-line-length = "200"
string-quote = "double"

[tool.pylint.messages_control]
# no-member to remove false positives with objects constructed via google's discovery protocol
disable = [
	"bad-continuation",
	"duplicate-code",
	"fixme",
	"invalid-name",
	"len-as-condition",
	"logging-format-interpolation",
	"logging-fstring-interpolation",
	"missing-docstring",
	"relative-beyond-top-level"
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
